image: openjdk:17.0.2-slim

stages:
  - build-image
  - deploy

build-image:
  tags:
    - js
  stage: build-image
  image: docker:20.10.17-git
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build --build-arg HOST_NAME --build-arg ALCOHOLIC_HOST --build-arg ALCOHOLIC_PORT --build-arg ALCOPARTY_HOST --build-arg ALCOPARTY_PORT -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID .
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID
  only:
    - main

kuber-dev:
  stage: deploy
  trigger:
    project: /buhinder/alco-env
    branch: main
  variables:
    APPLICATION_BRANCH: $CI_COMMIT_REF_NAME
    APPLICATION_VERSION: $CI_PIPELINE_IID
    SERVICE_NAME: $CI_PROJECT_NAME
  allow_failure: true
  only:
    - dev
    - main

